apiVersion: v1
kind: Service
metadata:
  name: exam-app # Sets service name
  labels:
    app: exam-app # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  ports:
    - port: 8081 # Sets port to run the exam-app 
  selector:
    app: exam-app